// Code generated by "stringer -type StateType -output stringer.go"; DO NOT EDIT.

package raft

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FollowerState-1]
	_ = x[CandidateState-2]
	_ = x[LeaderState-3]
}

const _StateType_name = "FollowerStateCandidateStateLeaderState"

var _StateType_index = [...]uint8{0, 13, 27, 38}

func (i StateType) String() string {
	i -= 1
	if i >= StateType(len(_StateType_index)-1) {
		return "StateType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _StateType_name[_StateType_index[i]:_StateType_index[i+1]]
}
